### ISSUE TITLE
suddenly, failures

### ISSUE THREAD

**Issue by d-w-liu** [AllenSWDB/allenswdb.github.io#129]
[/physiology/ophys/visual-behavior/VBO-ExperimentData](https://allenswdb.github.io/physiology/ophys/visual-behavior/VBO-ExperimentData.html#plot-example-cell-activity-with-stimuli-and-behavior)
[/physiology/ophys/visual-behavior/VBO-Tutorial-Compare-trial-types](https://allenswdb.github.io/physiology/ophys/visual-behavior/VBO-Tutorial-Compare_trial_types.html#here-is-a-hit-trial)
[/physiology/ophys/visual-behavior/VB-BehaviorSessionData](https://allenswdb.github.io/physiology/ophys/visual-behavior/VB-BehaviorSessionData.html#plot-behavior-data-for-a-portion-of-one-session)
[/physiology/ephys/visual-behavior/VBN-Tutorial-Analyzing_LFP_Data](https://allenswdb.github.io/physiology/ephys/visual-behavior/VBN-Tutorial-Analyzing_LFP_Data.html#aligning-lfp-data-to-units)

all are having execution failures now that seemingly started out of nowhere. None of the files have been changed in two months, but the code is now returning NaNs or index out of range errors where it didn't before.

**Comment by JEElsner** [comment]
| **Page**                                                                                                                                                           | **Status**                 |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------- |
| [VBO-ExperimentData](https://allenswdb.github.io/physiology/ophys/visual-behavior/VBO-ExperimentData.html#plot-example-cell-activity-with-stimuli-and-behavior)    | Fixed by PR #41 and/or #86 |
| [VBO-Tutorial-Compare-trial-types](https://allenswdb.github.io/physiology/ophys/visual-behavior/VBO-Tutorial-Compare_trial_types.html#here-is-a-hit-trial)         |                            |
| [VB-BehaviorSessionData](https://allenswdb.github.io/physiology/ophys/visual-behavior/VB-BehaviorSessionData.html#plot-behavior-data-for-a-portion-of-one-session) | Fixed by PR #41            |
| [/VBN-Tutorial-Analyzing_LFP_Data](https://allenswdb.github.io/physiology/ephys/visual-behavior/VBN-Tutorial-Analyzing_LFP_Data.html#aligning-lfp-data-to-units)   |                            |
