### ISSUE TITLE
Add missing citations / content

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#60]
VC2p: "cite What other 85% are doing etc." and "more here, with references!"

VC2p Visual stimuli: "CITATIONS HERE"

VCN Receptive fields: "This section is not yet complete, but you can use the precomputed metrics provided..."

CTLUT: "(CITATIONS)"

**Comment by JEElsner** [comment]
- [ ] VC2p: "cite What other 85% are doing etc." and "more here, with references!"
- [x] VC2p Visual stimuli: "CITATIONS HERE"
- [ ] VCN Receptive fields: "This section is not yet complete, but you can use the precomputed metrics provided..."
- [ ] CTLUT: "(CITATIONS)"
- [x] Visual Stimuli List: Natural Scenes
- [x] VC2p background: Hubel & Wiesel

Kind of blocked on the other ones because I don't know what papers to cite or what extra information to a add.

**Comment by saskiad** [comment]
@saskiad provide link to citation
